### Send POST request with json body
POST http://localhost:8080/api/patients
Content-Type: application/json

{
  "name": "test From Client"
}

### send a get to retrieve a patient
GET http://localhost:8080/api/patients/6